name: Deploy ReanHel Midterm Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Get the files from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload the HTML/CSS website
      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Deploy the website
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
